SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

USE CONSTRUCT;

DROP TABLE IF EXISTS BUSINESS_REG;
DROP TABLE IF EXISTS CONSTRUCT_CORP_REG;
DROP TABLE IF EXISTS CONSTRUCT_EMPLOYEE;
DROP TABLE IF EXISTS LOGIN;
DROP TABLE IF EXISTS CONSTRUCT_CORP;
DROP TABLE IF EXISTS CONSTRUCT_CORP_REG_INFO;
DROP TABLE IF EXISTS CONSTRUCT_PROJECT;
DROP TABLE IF EXISTS CORP_REG_BUSINESS;
DROP TABLE IF EXISTS CORP_INFO;
DROP TABLE IF EXISTS JOIN_PERSON;
DROP TABLE IF EXISTS JOIN_CORP;
DROP TABLE IF EXISTS PROJECT_INFO;
DROP TABLE IF EXISTS CONSTRUCT_EMPLOYEE;


DROP TABLE IF EXISTS WORKER_NODE;
CREATE TABLE WORKER_NODE
(
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'auto increment id',
    HOST_NAME VARCHAR(64) NOT NULL COMMENT 'host name',
    PORT VARCHAR(64) NOT NULL COMMENT 'port',
    TYPE INT NOT NULL COMMENT 'node type: CONTAINER(1), ACTUAL(2), FAKE(3)',
    LAUNCH_DATE DATE NOT NULL COMMENT 'launch date',
    MODIFIED TIMESTAMP NOT NULL COMMENT 'modified time',
    CREATED TIMESTAMP NOT NULL COMMENT 'created time',
    PRIMARY KEY(ID)
)
    COMMENT='DB WorkerID Assigner for UID Generator',ENGINE = INNODB;

/* Create Tables */

CREATE TABLE BUSINESS_REG
(
    CORP_TYPE varchar(16) NOT NULL,
    BUSINESS_ID bigint NOT NULL,
    REG_ID bigint NOT NULL,
    -- DELETE
    -- MODIFY
    -- CREATE
    -- QUOTED
    OPERATE varchar(6) NOT NULL COMMENT 'DELETE
MODIFY
CREATE
QUOTED',
    PRIMARY KEY (CORP_TYPE, BUSINESS_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CONSTRUCT_CORP
(
	CORP_CODE bigint NOT NULL,
	CORP_INFO bigint NOT NULL,
	ENABLE boolean NOT NULL,
	TYPES varchar(128) NOT NULL,
	DATA_TIME timestamp NOT NULL,
	PRIMARY KEY (CORP_CODE)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CONSTRUCT_CORP_REG
(
	CORP_CODE bigint NOT NULL,
	CORP_TYPE varchar(16) NOT NULL,
	REG_ID bigint NOT NULL,
	PRIMARY KEY (CORP_CODE, CORP_TYPE)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CONSTRUCT_CORP_REG_INFO
(
    REG_DATE_TO date NOT NULL,
    REG_TIME datetime NOT NULL,
    LEVEL int,
    LEVEL_NUMBER varchar(32),
    ID bigint NOT NULL,
    PREVIOUS bigint,
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CONSTRUCT_EMPLOYEE
(
    IDENTIFY_TYPE varchar(16) NOT NULL,
    IDENTIFY_NUMBER varchar(32),
    NAME varchar(64) NOT NULL,
    TEL varchar(16),
    CORP_CODE bigint NOT NULL,
    DATA_TIME timestamp NOT NULL,
    MANAGER boolean NOT NULL,
    USERNAME varchar(32) NOT NULL,
    ID bigint NOT NULL,
    VALID boolean NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CORP_INFO
(
	ID bigint NOT NULL,
	REG_ID_TYPE varchar(16) NOT NULL,
	REG_ID_NUMBER varchar(32) NOT NULL,
	OWNER_NAME varchar(32) NOT NULL,
	OWNER_ID_TYPE varchar(16) NOT NULL,
	OWNER_ID_NUMBER varchar(32),
	ADDRESS varchar(256),
	TEL varchar(16),
	NAME varchar(128) NOT NULL,
	PREVIOUS bigint,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CORP_REG_BUSINESS
(
    BUSINESS_ID bigint NOT NULL,
    CORP_CODE bigint NOT NULL,
    CREATE_TIME datetime NOT NULL,
    REG_TIME datetime NOT NULL,
    -- OLD
    -- OLE
    -- BIZ
    SOURCE varchar(8) NOT NULL COMMENT 'OLD
OLE
BIZ',
    STATUS varchar(8),
    INFO boolean NOT NULL,
    CORP_INFO bigint NOT NULL,
    TAGS varchar(512),
    APPLY_TIME datetime,
    PRIMARY KEY (BUSINESS_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;





/* Create Foreign Keys */

ALTER TABLE CONSTRUCT_CORP_REG
	ADD FOREIGN KEY (CORP_CODE)
	REFERENCES CONSTRUCT_CORP (CORP_CODE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CONSTRUCT_EMPLOYEE
	ADD FOREIGN KEY (CORP_CODE)
	REFERENCES CONSTRUCT_CORP (CORP_CODE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BUSINESS_REG
	ADD FOREIGN KEY (REG_ID)
	REFERENCES CONSTRUCT_CORP_REG_INFO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CONSTRUCT_CORP_REG
	ADD FOREIGN KEY (REG_ID)
	REFERENCES CONSTRUCT_CORP_REG_INFO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CONSTRUCT_CORP_REG_INFO
	ADD FOREIGN KEY (PREVIOUS)
	REFERENCES CONSTRUCT_CORP_REG_INFO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CONSTRUCT_CORP
	ADD FOREIGN KEY (CORP_INFO)
	REFERENCES CORP_INFO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CORP_INFO
	ADD FOREIGN KEY (PREVIOUS)
	REFERENCES CORP_INFO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CORP_REG_BUSINESS
	ADD FOREIGN KEY (CORP_INFO)
	REFERENCES CORP_INFO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BUSINESS_REG
	ADD FOREIGN KEY (BUSINESS_ID)
	REFERENCES CORP_REG_BUSINESS (BUSINESS_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE CONSTRUCT_EMPLOYEE
    ADD FOREIGN KEY (CORP_CODE)
        REFERENCES CONSTRUCT_CORP (CORP_CODE)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;

SET SESSION FOREIGN_KEY_CHECKS=1;