SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP DATABASE IF EXISTS CONSTRUCT;
CREATE DATABASE CONSTRUCT;
USE CONSTRUCT;

SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */


DROP TABLE IF EXISTS CONSTRUCT_PROJECT;
DROP TABLE IF EXISTS PROJECT_JOIN_PERSON;
DROP TABLE IF EXISTS PROJECT_JOIN_CORP;
DROP TABLE IF EXISTS PROJECT_REG_BUSINESS;

CREATE TABLE CONSTRUCT_PROJECT
(
    PROJECT_CODE varchar(32) NOT NULL,
    ENABLE boolean NOT NULL,
    DATA_TIME timestamp NOT NULL,
    BUSINESS_ID bigint NOT NULL,
    PRIMARY KEY (PROJECT_CODE)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE PROJECT_JOIN_CORP
(
    ID bigint NOT NULL,
    OUTSIDE_TEAM_FILE varchar(32),
    OUT_LEVEL boolean NOT NULL,
    OUT_LEVEL_FILE varchar(32),
    CORP_CODE varchar(32) NOT NULL,
    CORP_TYPE varchar(16) NOT NULL,
    NAME varchar(128) NOT NULL,
    REG_ID_TYPE varchar(16) NOT NULL,
    REG_ID_NUMBER varchar(32) NOT NULL,
    LEVEL int NOT NULL,
    CONTACTS varchar(64),
    TEL varchar(16),
    BUSINESS_ID bigint NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE PROJECT_JOIN_PERSON
(
    ID bigint NOT NULL,
    CORP bigint NOT NULL,
    JOIN_TYPE varchar(16) NOT NULL,
    LEVEL varchar(8),
    JOB varchar(32) NOT NULL,
    NAME varchar(64) NOT NULL,
    IDENTIFY_TYPE varchar(16) NOT NULL,
    IDENTIFY_NUMBER varchar(32) NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE PROJECT_REG_BUSINESS
(
    PROJECT_CODE varchar(32) NOT NULL,
    NAME varchar(256) NOT NULL,
    ADDRESS varchar(512),
    TYPE varchar(32),
    PROPERTY varchar(32),
    CONTRACT_AREA decimal(19,2),
    ALL_AREA decimal(19,2),
    GROUND_FLOOR_COUNT int,
    UNDER_FLOOR_COUNT int,
    BEGIN_DATE date,
    COMPLETED_DATE date,
    TENDER varchar(32),
    STRUCTURE varchar(32),
    COSTS decimal(18,2),
    MAIN_PROJECT boolean,
    MAIN_PROJECT_LEVEL varchar(16),
    MAIN_PROJECT_FILE varchar(32),
    MEMO varchar(512),
    HEIGHT decimal(19,2),
    BUSINESS_ID bigint NOT NULL,
    PREVIOUS bigint,
    CREATE_TIME datetime NOT NULL,
    REG_TIME datetime,
    APPLY_TIME datetime,
    -- OLD
    -- OLE
    -- BIZ
    SOURCE varchar(3) NOT NULL COMMENT 'OLD
OLE
BIZ',
    STATUS varchar(8) NOT NULL,
    TAGS varchar(512),
    PRIMARY KEY (BUSINESS_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


/* Create Foreign Keys */

ALTER TABLE PROJECT_JOIN_PERSON
    ADD FOREIGN KEY (CORP)
        REFERENCES PROJECT_JOIN_CORP (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE CONSTRUCT_PROJECT
    ADD FOREIGN KEY (BUSINESS_ID)
        REFERENCES PROJECT_REG_BUSINESS (BUSINESS_ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE PROJECT_JOIN_CORP
    ADD FOREIGN KEY (BUSINESS_ID)
        REFERENCES PROJECT_REG_BUSINESS (BUSINESS_ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE PROJECT_REG_BUSINESS
    ADD FOREIGN KEY (PREVIOUS)
        REFERENCES PROJECT_REG_BUSINESS (BUSINESS_ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;






SET SESSION FOREIGN_KEY_CHECKS=1;