SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

USE CONSTRUCT;

SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS BUILD;
DROP TABLE IF EXISTS BUILD_REG_AND_INFO;
DROP TABLE IF EXISTS BUILD_INFO;
DROP TABLE IF EXISTS BUILD_REG;

DROP TABLE IF EXISTS CONSTRUCT_PROJECT;
DROP TABLE IF EXISTS PROJECT_INFO_REG;
DROP TABLE IF EXISTS PROJECT_JOIN_PERSON;
DROP TABLE IF EXISTS PROJECT_JOIN_CORP;
DROP TABLE IF EXISTS PROJECT_JOIN_CORP_INFO;
DROP TABLE IF EXISTS PROJECT_JOIN_REG;
DROP TABLE IF EXISTS PROJECT_REG;




/* Create Tables */

DROP TABLE IF EXISTS WORKER_NODE;
CREATE TABLE WORKER_NODE
(
    ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'auto increment id',
    HOST_NAME VARCHAR(64) NOT NULL COMMENT 'host name',
    PORT VARCHAR(64) NOT NULL COMMENT 'port',
    TYPE INT NOT NULL COMMENT 'node type: CONTAINER(1), ACTUAL(2), FAKE(3)',
    LAUNCH_DATE DATE NOT NULL COMMENT 'launch date',
    MODIFIED TIMESTAMP NOT NULL COMMENT 'modified time',
    CREATED TIMESTAMP NOT NULL COMMENT 'created time',
    PRIMARY KEY(ID)
)
    COMMENT='DB WorkerID Assigner for UID Generator',ENGINE = INNODB;



CREATE TABLE BUILD
(
    BUILD_CODE bigint NOT NULL,
    INFO bigint NOT NULL,
    REG_TIME datetime NOT NULL,
    PROJECT_CODE bigint NOT NULL,
    ENABLE boolean NOT NULL,
    VERSION int NULL,
    PRIMARY KEY (BUILD_CODE)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE BUILD_INFO
(
    ID bigint NOT NULL,
    NAME varchar(32),
    STRUCTURE varchar(16) NOT NULL,
    GROUND_FLOOR_COUNT int,
    UNDER_FLOOR_COUNT int,
    HEIGHT decimal(19,2),
    ALL_AREA decimal(19,2),
    GROUND_AREA decimal(19,2),
    UNDER_AREA decimal(19,2),
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE BUILD_REG
(
    ID bigint NOT NULL,
    REG_TIME datetime,
    COUNT int NOT NULL,
    ON_AREA decimal(19,2) NOT NULL,
    UNDER_AREA decimal(19,2) NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE BUILD_REG_AND_INFO
(
    ID bigint NOT NULL,
    REG bigint NOT NULL,
    -- DELETE
    -- MODIFY
    -- CREATE
    -- QUOTED
    OPERATE varchar(6) NOT NULL COMMENT 'DELETE
MODIFY
CREATE
QUOTED',
    BUILD_INFO bigint NOT NULL,
    PREVIOUS bigint NULL,
    BUILD_CODE bigint NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CONSTRUCT_PROJECT
(
    PROJECT_CODE bigint NOT NULL,
    ENABLE boolean NOT NULL,
    INFO bigint NOT NULL,
    CORP bigint NOT NULL,
    DEVELOPER bigint NOT NULL,
    REG_TIME datetime NOT NULL,
    BUILD bigint NOT NULL,
    PRIMARY KEY (PROJECT_CODE)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;



CREATE TABLE PROJECT_INFO_REG
(
    ID bigint NOT NULL,
    REG_TIME datetime,
    PREVIOUS bigint,
    PROPERTY varchar(6) NOT NULL,
    NAME varchar(256) NOT NULL,
    ADDRESS varchar(512) NOT NULL,
    TYPE varchar(19) NOT NULL,
    TYPE_LEVEL int,
    ALL_AREA decimal(19,2),
    BEGIN_DATE date,
    COMPLETED_DATE date,
    TENDER varchar(32),
    COSTS decimal(18,2),
    MAIN_PROJECT_LEVEL varchar(8) NOT NULL,
    MAIN_PROJECT_FILE varchar(32),
    MODIFY_FIT boolean NULL,
    MODIFY_WARM boolean NULL,
    MODIFY_USE boolean NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE PROJECT_JOIN_CORP
(
    JOIN_ID bigint NOT NULL,
    OUTSIDE_TEAM_FILE varchar(32),
    OUT_LEVEL boolean,
    OUT_LEVEL_FILE varchar(32),
    CORP_CODE bigint NOT NULL,
    CORP_TYPE varchar(16) NOT NULL,
    CONTACTS varchar(64),
    TEL varchar(16),
    REG bigint NOT NULL,
    PRIMARY KEY (JOIN_ID),
    CONSTRAINT UNIQUE_CORP_PROPERTY_REG UNIQUE (CORP_CODE, CORP_TYPE, REG)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE PROJECT_JOIN_CORP_INFO
(
    NAME varchar(128) NOT NULL,
    REG_ID_TYPE varchar(16) NOT NULL,
    REG_ID_NUMBER varchar(32) NOT NULL,
    LEVEL int NOT NULL,
    JOIN_ID bigint NOT NULL,
    OWNER_ID_TYPE varchar(16) NOT NULL,
    OWNER_ID_NUMBER varchar(32),
    OWNER_NAME varchar(32),
    PRIMARY KEY (JOIN_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE PROJECT_JOIN_PERSON
(
    JOIN_ID bigint NOT NULL,
    CORP bigint NOT NULL,
    JOIN_TYPE varchar(16) NOT NULL,
    LEVEL varchar(8),
    JOB varchar(32) NOT NULL,
    NAME varchar(64) NOT NULL,
    IDENTIFY_TYPE varchar(16) NOT NULL,
    IDENTIFY_NUMBER varchar(32) NOT NULL,
    PRIMARY KEY (JOIN_ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE PROJECT_JOIN_REG
(
    ID bigint NOT NULL,
    PREVIOUS bigint,
    REG_TIME datetime,
    TAGS varchar(1024),
    CORPS text,
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE PROJECT_REG
(
    CREATE_TIME datetime NOT NULL,
    REG_TIME datetime,
    APPLY_TIME datetime,
    -- OLD
    -- OLE
    -- BIZ
    SOURCE varchar(8) NOT NULL COMMENT 'OLD
OLE
BIZ',
    STATUS varchar(8) NOT NULL,
    TAGS varchar(1024),
    PROJECT_CODE bigint NOT NULL,
    ID bigint NOT NULL,
    TYPE varchar(7) NOT NULL,
    CORP_MASTER boolean NOT NULL,
    INFO_MASTER boolean NOT NULL,
    BUILD_MASTER boolean NOT NULL,
    INFO bigint NOT NULL,
    CORP bigint NOT NULL,
    BUILD bigint NOT NULL,
    PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;



/* Create Foreign Keys */

ALTER TABLE BUILD
    ADD FOREIGN KEY (INFO)
        REFERENCES BUILD_INFO (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE BUILD_REG_AND_INFO
    ADD FOREIGN KEY (BUILD_INFO)
        REFERENCES BUILD_INFO (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE BUILD_REG_AND_INFO
    ADD FOREIGN KEY (PREVIOUS)
        REFERENCES BUILD_INFO (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE BUILD_REG_AND_INFO
    ADD FOREIGN KEY (REG)
        REFERENCES BUILD_REG (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE CONSTRUCT_PROJECT
    ADD FOREIGN KEY (BUILD)
        REFERENCES BUILD_REG (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE PROJECT_REG
    ADD FOREIGN KEY (BUILD)
        REFERENCES BUILD_REG (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;

ALTER TABLE CONSTRUCT_PROJECT
    ADD FOREIGN KEY (INFO)
        REFERENCES PROJECT_INFO_REG (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE PROJECT_INFO_REG
    ADD FOREIGN KEY (PREVIOUS)
        REFERENCES PROJECT_INFO_REG (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE PROJECT_REG
    ADD FOREIGN KEY (INFO)
        REFERENCES PROJECT_INFO_REG (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE CONSTRUCT_PROJECT
    ADD FOREIGN KEY (DEVELOPER)
        REFERENCES PROJECT_JOIN_CORP (JOIN_ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE PROJECT_JOIN_CORP_INFO
    ADD FOREIGN KEY (JOIN_ID)
        REFERENCES PROJECT_JOIN_CORP (JOIN_ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE PROJECT_JOIN_PERSON
    ADD FOREIGN KEY (CORP)
        REFERENCES PROJECT_JOIN_CORP (JOIN_ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE CONSTRUCT_PROJECT
    ADD FOREIGN KEY (CORP)
        REFERENCES PROJECT_JOIN_REG (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE PROJECT_JOIN_CORP
    ADD FOREIGN KEY (REG)
        REFERENCES PROJECT_JOIN_REG (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE PROJECT_JOIN_REG
    ADD FOREIGN KEY (PREVIOUS)
        REFERENCES PROJECT_JOIN_REG (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;


ALTER TABLE PROJECT_REG
    ADD FOREIGN KEY (CORP)
        REFERENCES PROJECT_JOIN_REG (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;

SET SESSION FOREIGN_KEY_CHECKS=1;